language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: hi
    token:f56f1af84cf704a88d9f5f6e53e7655721df2b6c
      secure: "your_token_encrypted_with_travis_encrypt_tool"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
